//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchShop_Vasilyev_isp27
{
    using System;
    using System.Collections.Generic;
    
    public partial class Изделия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Изделия()
        {
            this.Состав_Поставки = new HashSet<Состав_Поставки>();
            this.Состав_Продажи = new HashSet<Состав_Продажи>();
        }
    
        public int ID_Изделия { get; set; }
        public string Название { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<double> Вес { get; set; }
        public Nullable<double> Диаметр { get; set; }
        public string Описание { get; set; }
        public Nullable<int> ID_Бренда { get; set; }
        public Nullable<int> ID_Вида { get; set; }
        public Nullable<int> ID_Материла { get; set; }
        public Nullable<int> ID_Категории { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<int> Гарантия { get; set; }
    
        public virtual Бренд Бренд { get; set; }
        public virtual Вид_изделия Вид_изделия { get; set; }
        public virtual Категория Категория { get; set; }
        public virtual Материал_Изделия Материал_Изделия { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_Поставки> Состав_Поставки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_Продажи> Состав_Продажи { get; set; }
    }
}
