//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchShop_Vasilyev_isp27
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Поставка()
        {
            this.Состав_Поставки = new HashSet<Состав_Поставки>();
        }
    
        public int ID_Поставки { get; set; }
        public Nullable<int> ID_Поставщика { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
    
        public virtual Поставщик Поставщик { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_Поставки> Состав_Поставки { get; set; }
    }
}
