//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchShop_Vasilyev_isp27
{
    using System;
    using System.Collections.Generic;
    
    public partial class Состав_Поставки
    {
        public Nullable<int> ID_Поставки { get; set; }
        public Nullable<int> ID_Изделия { get; set; }
        public Nullable<int> Количество1 { get; set; }
        public int ID_Состава_Поставки { get; set; }
    
        public virtual Изделия Изделия1 { get; set; }
        public virtual Поставка Поставка { get; set; }
    }
}
